pipeline {
    environment {
        JAVA_TOOL_OPTIONS = "-Duser.home=/home/jenkins"
    }
    agent {
        dockerfile {
            label "docker"
            args "-v /tmp/maven:/home/jenkins/.m2 -e MAVEN_CONFIG=/home/jenkins/.m2"
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout your code repository
                git url: 'https://github.com/subhashis2018/springboot_cicd_1.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project
                sh "${MAVEN_HOME}/bin/mvn clean package"
            }
        }
        
        stage('Test') {
            steps {
                // Run tests
                sh "${MAVEN_HOME}/bin/mvn test"
            }
        }
    }
    
    post {
        always {
            cleanWs() // Clean up workspace after build
        }
    }
}
