pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your version control system
                git ' https://github.com/subhashis2018/springboot_cicd_1.git'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project
                sh 'mvn clean install'
            }
        }
        
        stage('Test') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                // Run tests using Maven
                sh 'mvn package'
            }
        }
        
        stage('Deploy') {
            steps {
                // Example: Deploy the built artifact to a server
                // sh 'mvn deploy'
            }
        }
    }
    
    post {
        always {
            // Clean up workspace
            cleanWs()
        }
        
        success {
            // Perform actions on successful build
            echo 'Build successful!'
        }
        
        failure {
            // Perform actions on failed build
            echo 'Build failed!'
        }
    }
}
