pipeline{
    agent none

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven 'mymaven'
    }
    parameters {
        booleanParam(name:'executeTests', defaultValue: true, description:'decide to run tc')
    }

    // environment {
    //     PACKAGE_SERVER = 'ec2-user@172.31.7.45'
    // }

    stages{
        stage("compile"){
            agent { label 'linux_slave' }
            steps{
                echo "========compiling========"
                 sh 'mvn compile'
            }
        }
        stage("test"){
            agent any
            when {
                expression {
                    params.executeTests == true
                }
            }
            steps {
                script {
                    echo 'Test the code'
                    sh 'mvn test'
                }
            }
        }
        stage("package"){
            agent any
            steps{
                sh 'mvn package'
            }
        }
        stage("deploy"){
            steps{
                echo "========deploying========"
            }
        }
    }
}