pipeline{
    agent none
    tools {
        jdk 'myjava'
        maven 'mymaven'
    }
    parameters{
          booleanParam(name:'executeTests', defaultValue: true, description:'decide to run tc')
    }
    stages{
        stage("compile"){
            agent any
            steps{
                echo "========compileing========"
                sh 'git clone  https://github.com/subhashis2018/springboot_cicd_1.git'
                sh 'cd springboot_cicd_1'
                sh 'mvn compile'
            }
        }
        stage("test"){
            agent any
            steps{
                echo "========executing test========"
                sh 'mvn test'
            }
            post{
                success{
                    echo "========test executed successfully========"
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage("package"){
            agent any
            steps{
                echo "========packageing========"
                sh 'mvn package'
            }
            post{
                success{
                    echo "========package successfull========"
                }
            }
        }
        stage("deploy"){
            agent any
            steps{
                echo "========executing deploy========"
            }
            post{
                success{
                    echo "========deployed successfully========"
                }
            }
        }
    }
   
}