pipeline {
    environment {
        JAVA_TOOL_OPTIONS = "-Duser.home=/home/jenkins"
    }
    agent {
        dockerfile {
            label "docker"
            args "-v /tmp/maven:/home/jenkins/.m2 -e MAVEN_CONFIG=/home/jenkins/.m2"
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout your code repository
                git url: 'https://github.com/subhashis2018/springboot_cicd_1.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project
                sh "${MAVEN_HOME}/bin/mvn clean package"
            }
        }
        
        stage('Test') {
            steps {
                // Run tests
                sh "${MAVEN_HOME}/bin/mvn test"
            }
        }
        
        // stage('Docker Build') {
        //     steps {
        //         // Build Docker image
        //         script {
        //             docker.build("${DOCKER_IMAGE}")
        //         }
        //     }
        // }
        
        // stage('Deploy') {
        //     steps {
        //         // Push Docker image to registry or deploy to server
        //         script {
        //             docker.withRegistry('https://your.registry.url', 'your_registry_credentials') {
        //             docker.image("${DOCKER_IMAGE}").push()
        //             }
        //         }
        //     }
        }
        post{
            always{
                cleanWs()
            }
        }
    }
    


