pipeline {
    agent any

    tools{
        git 'mygit'
        maven 'mymaven'
        jdk  'myjava'
    }
    
    environment {
        // Define environment variables
        DOCKER_IMAGE = 'subhashis2022/springboot_cicd_1:1.0.0'
        MAVEN_HOME = tool 'mymaven'
        DOCKER_REGISTRY_URL=''
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout your code repository
                 git url: 'https://github.com/subhashis2018/springboot_cicd_1.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project
                sh "${MAVEN_HOME}/bin/mvn clean package"
            }
        }
        
        stage('Test') {
            steps {
                // Run tests
                sh "${MAVEN_HOME}/bin/mvn test"
            }
        }
        
        // stage('Docker Build') {
        //     steps {
        //         // Build Docker image
        //         script {
        //             docker.build("${DOCKER_IMAGE}")
        //         }
        //     }
        // }
        
        // stage('Deploy') {
        //     steps {
        //         // Push Docker image to registry or deploy to server
        //         script {
        //             docker.withRegistry('https://your.registry.url', 'your_registry_credentials') {
        //             docker.image("${DOCKER_IMAGE}").push()
        //             }
        //         }
        //     }
        }
    }
    


