pipeline {
    agent any
    options {
        // Timeout counter starts AFTER agent is allocated
        timeout(time: 1, unit: 'SECONDS')
    }
    stages {
        stage('Compile') {
            steps {
                echo 'Compiling ..................'
            }
        }
        stage('UnitTesting') {
            steps {
                echo 'UnitTesting ...........'
            }
        }
        stage('JACOCO') {
            steps {
                echo 'JACOCO Report generating.......................'
            }
        }
        stage('SonarReport') {
            steps {
                echo 'SonarReport.............'
            }
        }
        stage('PushToPCF') {
            steps {
                echo 'Pushing to PCF foundation...............'
            }
        }
    }
}
