pipeline {
    agent any
    tools {
        gradle 'mygradle'
        jdk 'myjava'
    }
    stages {
        // stage("Checkout") {
        //     steps {
        //         // Checkout the source code from your version control system
        //         git url: 'https://github.com/subhashis2018/springboot-cicd-gradle-2.git', branch: 'main'
        //     }
        // }
        stage("Compile") {
            steps {
                echo "========Compiling========"
                sh 'gradle init'
                //sh 'gradle -d clean'
                sh 'gradle  build '
                sh 'gradle --stacktrace'
            }
            post {
                always {
                    echo "========Always========"
                    cleanWs()
                }
            }
        }
        stage("Test") {
            steps {
                echo "========Testing========"
                sh 'gradle check'
                sh 'gradle test --continue'
            }
            post {
                always {
                    echo "========Always========"
                    cleanWs()
                }
            }
        }
        stage("Package") {
            steps {
                echo "========Packaging========"
                sh 'gradle projects'
            }
            post {
                always {
                    echo "========Always========"
                    cleanWs()
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "========Deploying========"
            }
            post {
                always {
                    echo "========Always========"
                    cleanWs()
                }
            }
        }
    }
}
