pipeline{
    agent any
    tools{
      gradle 'mygradle'
      jdk 'myjava'
    }
    environment{

    }
    stages{
        stage("Checkout"){
            steps{
                 // Checkout the source code from your version control system
                 git url: 'https://github.com/subhashis2018/springboot-cicd-gradle-1.git', branch: 'main'
            }
        }
        stage("Compile"){
            steps{
                echo "========Compileing========"
               sh  'gradle clean build --stacktrace --info'
            }
            post{
                always{
                    echo "========always========"
                }
            }
        }
        stage("Test"){
            steps{
                echo "========Testing========"
                sh 'gradle check'
                sh 'gradle test --continue --full-stacktrace'
            }
            post{
                always{
                    echo "========always========"
                }
            }
        }
        stage("Package"){
            steps{
                echo "========Packageing========"
                sh 'gradle projects'
            }
            post{
                always{
                    echo "========always========"
                }
            }
        }
        stage("Deploy"){
            steps{
                echo "========Deploying========"
            }
            post{
                always{
                    echo "========always========"
                }
            }
        }
    }
}